# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_monster
    ports:
    - "5432:5432"
    volumes:
    - my_dbdata:/var/lib/postgresql/data
volumes:
    my_dbdata: